#
# explaining the makefile:
# target: prerequisites - the rule head
# $@ - means the target
# $^ - means all prerequisites
# $< - means just the first prerequisite
# ar - a Linux tool to create, modify, and extract from archives see the man pages for further information. The options in this case mean:
# r - replace files existing inside the archive
# c - create a archive if not already existent
# s - create an object-file index into the archive


TARGET = prog
LIBS = -lm
CC = gcc
CFLAGS = -g -Wall

.PHONY: default all clean

default: $(TARGET)
all: default

OBJECTS = $(patsubst %.c, %.o, $(wildcard *.c))
HEADERS = $(wildcard *.h)

%.o: %.c $(HEADERS)
    $(CC) $(CFLAGS) -c $< -o $@

.PRECIOUS: $(TARGET) $(OBJECTS)

$(TARGET): $(OBJECTS)
    $(CC) $(OBJECTS) -Wall $(LIBS) -o $@

clean:
	-rm -f *.o
	-rm -f $(TARGET)
